spring.application.name=Covoiturage
spring.datasource.url=jdbc:postgresql://localhost:5432/db_covoiturage
spring.datasource.username=postgres
spring.datasource.password=2012
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.main.allow-circular-references=true
#spring.h2.console.enabled=true
server.port=8044